### ISSUE TITLE
Describe setup with tinytex in README

### ISSUE THREAD

**Issue by jsta** [hughjonesd/latexdiffr#2]
Thanks for the package! I initially had trouble getting it to work with `tinytex` until I found your blogpost: https://medium.com/@davidhughjones/install-tinytex-on-appveyor-for-r-ce4012b9b1c1. What do you think about adding `tinytex` instructions to the README?

**Comment by hughjonesd** [comment]
Merged, though too late for 0.1.0... my bad! Thank you.
